version: '2'

services:
    masternode:
        image: nutellinoit/master-multichain:1.0
        stdin_open: true
        tty: true
        volumes:
            - ./params.dat:/root/params.dat
            - ./multichain.conf:/root/multichain.conf
        ports:
            - "7447:7447"
            - "8000:8000"
        environment:
            VIRTUAL_HOST: mulichain-master.docker
            VIRTUAL_PORT: 8000
            NOMECHAIN: ChainBusnet
    #explorer:
    #    image: nutellinoit/explorer-multichain:1.0
    #    stdin_open: true
    #    tty: true
    #    depends_on:
    #        - masternode
    #    ports:
    #        - "2750:2750"
    #    environment:
    #        VIRTUAL_HOST: multichain-explorer.docker
    #        VIRTUAL_PORT: 2750
    #    links:
    #        - masternode
    slavenode1:
        image: nutellinoit/node-multichain:1.0
        stdin_open: true
        tty: true
        depends_on:
            - masternode
        links:
            - masternode
        environment:
          CONNECT_TO: ChainBusnet@masternode:7447
    slavenode2:
        image: nutellinoit/node-multichain:1.0
        stdin_open: true
        tty: true
        depends_on:
            - masternode
        links:
            - masternode
        environment:
          CONNECT_TO: ChainBusnet@masternode:7447
