version: '2'

services:
    masternode:
        image: nutellinoit/master-multichain:1.3
        stdin_open: true
        tty: true
        volumes:
            - ./data/:/root/.multichain/
        ports:
            - "${CONNECT_PORT}:7447"
            - "${SETUP_default_rpc_port}:8000"
        environment:
            VIRTUAL_HOST: ${NOMECHAIN}.docker
            VIRTUAL_PORT: ${SETUP_default_rpc_port}
            NOMECHAIN: ${NOMECHAIN}
            #Params used only on creation
            SETUP_maximum_block_size: ${SETUP_maximum_block_size}
            SETUP_default_network_port: ${SETUP_default_network_port}
            SETUP_default_rpc_port: ${SETUP_default_rpc_port}
            SETUP_anyone_can_connect: ${SETUP_anyone_can_connect}
            SETUP_anyone_can_send: ${SETUP_anyone_can_send}
            SETUP_anyone_can_receive: ${SETUP_anyone_can_receive}
            SETUP_anyone_can_mine: ${SETUP_anyone_can_mine}
            SETUP_mining_diversity: ${SETUP_mining_diversity}
            SETUP_anyone_can_activate: ${SETUP_anyone_can_activate}
            #Per la connessione del pannello web
            SET_MULTICHAIN: ${SET_MULTICHAIN}
            RPCUSERVAR: ${RPCUSERVAR}
            RPCPASSWORDVAR: ${RPCPASSWORDVAR}
        restart: always
        networks:
            main:
              aliases:
                - node1
                - masternode
    explorer:
        image: nutellinoit/explorer-multichain:1.0
        stdin_open: true
        tty: true
        depends_on:
            - masternode
        ports:
            - "${EXPLORER_PORT}:2750"
        environment:
            VIRTUAL_HOST: ${NOMECHAIN}-explorer.docker
            VIRTUAL_PORT: 2750
            NOMECHAIN: ${NOMECHAIN}
            CONNECT_TO: ${NOMECHAIN}@masternode:7447
        links:
            - masternode
        restart: always
        networks:
            main:
              aliases:
                - explorer

    slavenode:
        image: nutellinoit/node-multichain:1.1
        stdin_open: true
        tty: true
        depends_on:
            - masternode
        links:
            - masternode
        environment:
          CONNECT_TO: ${NOMECHAIN}@masternode:7447
        restart: always
        networks:
          main:
            aliases:
              - slavenode
    web:
        image: nutellinoit/web-app-nginx-multichain:1.1
        ports:
            - "${NGINX_PORT}:80"
        networks:
          main:
            aliases:
              - web
        restart: always
    php:
        image: nutellinoit/web-app-php-multichain:1.1
        restart: always
        environment:
          RPCUSER: ${RPCUSERVAR}
          RPCPASSWORD: ${RPCPASSWORDVAR}
        networks:
          main:
            aliases:
              - php

networks:
    main:
