version: '2'

services:
    masternode:
        image: nutellinoit/master-multichain:1.3
        stdin_open: true
        tty: true
        volumes:
            - ./data/:/root/.multichain/
        ports:
            - "${CONNECT_PORT}:7447"
            - "${SETUP_default_rpc_port}:8000"
        environment:
            VIRTUAL_HOST: ${NOMECHAIN}.docker
            VIRTUAL_PORT: ${SETUP_default_rpc_port}
            NOMECHAIN: ${NOMECHAIN}
            #Params used only on creation
            SETUP_maximum_block_size: ${SETUP_maximum_block_size}
            SETUP_default_network_port: ${SETUP_default_network_port}
            SETUP_default_rpc_port: ${SETUP_default_rpc_port}
            SETUP_anyone_can_connect: ${SETUP_anyone_can_connect}
            SETUP_anyone_can_send: ${SETUP_anyone_can_send}
            SETUP_anyone_can_receive: ${SETUP_anyone_can_receive}
            SETUP_anyone_can_mine: ${SETUP_anyone_can_mine}
            SETUP_mining_diversity: ${SETUP_mining_diversity}
            SETUP_anyone_can_activate: ${SETUP_anyone_can_activate}
            #Per la connessione del pannello web
            SET_MULTICHAIN: ${SET_MULTICHAIN}
            RPCUSERVAR: ${RPCUSERVAR}
            RPCPASSWORDVAR: ${RPCPASSWORDVAR}
        restart: always
        networks:
            main:
              aliases:
                - node1
                - masternode
    explorer:
        image: nutellinoit/explorer-multichain:1.0
        stdin_open: true
        tty: true
        depends_on:
            - masternode
        ports:
            - "${EXPLORER_PORT}:2750"
        environment:
            VIRTUAL_HOST: ${NOMECHAIN}-explorer.docker
            VIRTUAL_PORT: 2750
            NOMECHAIN: ${NOMECHAIN}
            CONNECT_TO: ${NOMECHAIN}@masternode:7447
        links:
            - masternode
        restart: always
        networks:
            main:
              aliases:
                - explorer
    web:
        image: nutellinoit/web-app-nginx-multichain:1.1
        ports:
            - "${NGINX_PORT}:80"
        networks:
          main:
            aliases:
              - web
        restart: always
    php:
        image: nutellinoit/web-app-php-multichain:1.5
        restart: always
        environment:
          CONNECT_IP: masternode
          CONNECT_PORT: 8000
          NOMECHAIN: ${NOMECHAIN}
          SET_MULTICHAIN: ${SET_MULTICHAIN}
          RPCUSER: ${RPCUSERVAR}
          RPCPASSWORD: ${RPCPASSWORDVAR}
        networks:
          main:
            aliases:
              - php
    slavenode1:
        image: nutellinoit/node-multichain:1.1
        stdin_open: true
        tty: true
        depends_on:
            - masternode
        links:
            - masternode
        environment:
          CONNECT_TO: ${NOMECHAIN}@masternode:7447
          NOMECHAIN: ${NOMECHAIN}
          SET_MULTICHAIN: ${SET_MULTICHAIN}
          RPCUSERVAR: ${RPCUSERVAR}
          RPCPASSWORDVAR: ${RPCPASSWORDVAR}
        restart: always
        networks:
          main:
            aliases:
              - slavenode1
    web1:
        image: nutellinoit/web-app-nginx-multichain:1.1
        volumes:
            - ./site8500.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8500:80"
        networks:
          main:
            aliases:
              - web1
        restart: always
    php1:
        image: nutellinoit/web-app-php-multichain:1.5
        restart: always
        environment:
          CONNECT_IP: slavenode1
          CONNECT_PORT: 8000
          NOMECHAIN: ${NOMECHAIN}
          SET_MULTICHAIN: ${SET_MULTICHAIN}
          RPCUSER: ${RPCUSERVAR}
          RPCPASSWORD: ${RPCPASSWORDVAR}
        networks:
          main:
            aliases:
              - php1
    slavenode2:
        image: nutellinoit/node-multichain:1.1
        stdin_open: true
        tty: true
        depends_on:
            - masternode
        links:
            - masternode
        environment:
          CONNECT_TO: ${NOMECHAIN}@masternode:7447
          NOMECHAIN: ${NOMECHAIN}
          SET_MULTICHAIN: ${SET_MULTICHAIN}
          RPCUSERVAR: ${RPCUSERVAR}
          RPCPASSWORDVAR: ${RPCPASSWORDVAR}
        restart: always
        networks:
          main:
            aliases:
              - slavenode2
    web2:
        image: nutellinoit/web-app-nginx-multichain:1.1
        volumes:
            - ./site8501.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8501:80"
        networks:
          main:
            aliases:
              - web2
        restart: always
    php2:
        image: nutellinoit/web-app-php-multichain:1.5
        restart: always
        environment:
          CONNECT_IP: slavenode2
          CONNECT_PORT: 8000
          NOMECHAIN: ${NOMECHAIN}
          SET_MULTICHAIN: ${SET_MULTICHAIN}
          RPCUSER: ${RPCUSERVAR}
          RPCPASSWORD: ${RPCPASSWORDVAR}
        networks:
          main:
            aliases:
              - php2
    slavenode3:
        image: nutellinoit/node-multichain:1.1
        stdin_open: true
        tty: true
        depends_on:
            - masternode
        links:
            - masternode
        environment:
          CONNECT_TO: ${NOMECHAIN}@masternode:7447
          NOMECHAIN: ${NOMECHAIN}
          SET_MULTICHAIN: ${SET_MULTICHAIN}
          RPCUSERVAR: ${RPCUSERVAR}
          RPCPASSWORDVAR: ${RPCPASSWORDVAR}
        restart: always
        networks:
          main:
            aliases:
              - slavenode3
    web3:
        image: nutellinoit/web-app-nginx-multichain:1.1
        volumes:
            - ./site8502.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8502:80"
        networks:
          main:
            aliases:
              - web3
        restart: always
    php3:
        image: nutellinoit/web-app-php-multichain:1.5
        restart: always
        environment:
          CONNECT_IP: slavenode3
          CONNECT_PORT: 8000
          NOMECHAIN: ${NOMECHAIN}
          SET_MULTICHAIN: ${SET_MULTICHAIN}
          RPCUSER: ${RPCUSERVAR}
          RPCPASSWORD: ${RPCPASSWORDVAR}
        networks:
          main:
            aliases:
              - php3

networks:
    main:
