version: '2'

services:
    masternode:
        image: nutellinoit/master-multichain:1.2
        stdin_open: true
        tty: true
        volumes:
            - ./data/:/root/.multichain/
        ports:
            - "7447:7447"
            - "8000:8000"
        environment:
            VIRTUAL_HOST: mulichain-master.docker
            VIRTUAL_PORT: 8000
            NOMECHAIN: ticketchain
            #Params used only on creation
            SETUP_maximum_block_size: 1000000
            SETUP_default_network_port: 7447
            SETUP_default_rpc_port: 8000
            SETUP_anyone_can_connect: "true"
            SETUP_anyone_can_send: "false"
            SETUP_anyone_can_receive: "false"
            SETUP_anyone_can_mine: "true"
            SETUP_mining_diversity: 0.75
            SETUP_anyone_can_activate: "false"
        restart: always
    explorer:
        image: nutellinoit/explorer-multichain:1.0
        stdin_open: true
        tty: true
        depends_on:
            - masternode
        ports:
            - "2750:2750"
        environment:
            VIRTUAL_HOST: multichain-explorer.docker
            VIRTUAL_PORT: 2750
            NOMECHAIN: ticketchain
            CONNECT_TO: ticketchain@masternode:7447
        links:
            - masternode
        restart: always


    slavenode1:
        image: nutellinoit/node-multichain:1.1
        stdin_open: true
        tty: true
        depends_on:
            - masternode
        links:
            - masternode
        environment:
          CONNECT_TO: ticketchain@masternode:7447
        restart: always
    slavenode2:
        image: nutellinoit/node-multichain:1.1
        stdin_open: true
        tty: true
        depends_on:
            - masternode
        links:
            - masternode
        environment:
          CONNECT_TO: ticketchain@masternode:7447
        restart: always
    slavenode3:
        image: nutellinoit/node-multichain:1.1
        stdin_open: true
        tty: true
        depends_on:
            - masternode
        links:
            - masternode
        environment:
          CONNECT_TO: ticketchain@masternode:7447
        restart: always
