version: '2'

services:
    masternode:
        image: nutellinoit/master-multichain:1.3
        stdin_open: true
        tty: true
        volumes:
            - ./data/:/root/.multichain/
        ports:
            - "7447:7447"
            - "8000:8000"
        environment:
            VIRTUAL_HOST: mulichain-master.docker
            VIRTUAL_PORT: 8000
            NOMECHAIN: ticketchain
            #Params used only on creation
            SETUP_maximum_block_size: 1000000
            SETUP_default_network_port: 7447
            SETUP_default_rpc_port: 8000
            SETUP_anyone_can_connect: "true"
            SETUP_anyone_can_send: "false"
            SETUP_anyone_can_receive: "false"
            SETUP_anyone_can_mine: "true"
            SETUP_mining_diversity: 0.75
            SETUP_anyone_can_activate: "false"
            #Per la connessione del pannello web
            SET_MULTICHAIN: "yes"
            RPCUSERVAR: "rootuser"
            RPCPASSWORDVAR: "Htgm8W238727837ySMXdiyGeVeYPb4xoop93xsvshUs6WY"
        restart: always
        networks:
            main:
              aliases:
                - node1
                - masternode
    explorer:
        image: nutellinoit/explorer-multichain:1.0
        stdin_open: true
        tty: true
        depends_on:
            - masternode
        ports:
            - "2750:2750"
        environment:
            VIRTUAL_HOST: multichain-explorer.docker
            VIRTUAL_PORT: 2750
            NOMECHAIN: ticketchain
            CONNECT_TO: ticketchain@masternode:7447
        links:
            - masternode
        restart: always
        networks:
            main:
              aliases:
                - explorer

    slavenode:
        image: nutellinoit/node-multichain:1.1
        stdin_open: true
        tty: true
        depends_on:
            - masternode
        links:
            - masternode
        environment:
          CONNECT_TO: ticketchain@masternode:7447
        restart: always
        networks:
          main:
            aliases:
              - slavenode
    web:
        image: nutellinoit/web-app-nginx-multichain:1.1
        ports:
            - "8081:80"
        networks:
          main:
            aliases:
              - web
        restart: always
    php:
        image: nutellinoit/web-app-php-multichain:1.1
        restart: always
        environment:
          RPCUSER: "rootuser"
          RPCPASSWORD: "Htgm8W238727837ySMXdiyGeVeYPb4xoop93xsvshUs6WY"
        networks:
          main:
            aliases:
              - php

networks:
    main:
