apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.5.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: node1
  name: node1
spec:
  replicas: 5
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: node1
    spec:
      containers:
      - env:
        - name: CONNECT_TO
          value: ticketchain@192.168.50.1:7447
        - name: NOMECHAIN
          value: ticketchain
        - name: RPCPASSWORDVAR
          value: ji3i1o3j2o313j21i3jo12
        - name: RPCUSERVAR
          value: user1
        - name: SET_MULTICHAIN
          value: "yes"
        image: nutellinoit/node-multichain:1.1
        name: node1
        resources: {}
        stdin: true
        tty: true
      restartPolicy: Always
status: {}
