version: '2'
services:
    node1:
        image: nutellinoit/node-multichain:1.2
        stdin_open: true
        tty: true
        environment:
          CONNECT_TO: ${CONNECT_TO}
          NOMECHAIN: ${NOMECHAIN}
          SET_MULTICHAIN: ${SET_MULTICHAIN}
          RPCUSERVAR: ${RPCUSERVAR}
          RPCPASSWORDVAR: ${RPCPASSWORDVAR}
        restart: always
        volumes:
            - ${DATASAVEPATH}:/root/.multichain/
        networks:
          main:
            aliases:
              - node1
    web:
        image: nutellinoit/web-app-nginx-multichain:1.1
        ports:
            - "${NGINX_HOST_HTTP_PORT}:80"
        networks:
          main:
            aliases:
              - web
        restart: always
    php:
        image: nutellinoit/web-app-php-multichain:1.5
        restart: always
        environment:
          CONNECT_IP: node1
          CONNECT_PORT: 8000
          NOMECHAIN: ${NOMECHAIN}
          SET_MULTICHAIN: ${SET_MULTICHAIN}
          RPCUSER: ${RPCUSERVAR}
          RPCPASSWORD: ${RPCPASSWORDVAR}
        networks:
          main:
            aliases:
              - php
networks:
    main: